### ISSUE TITLE
Add file extensions

### ISSUE THREAD

**Issue by NathanDotTo** [CiscoDevNet/opendaylight-setup#1]
Hi Giles

You might like to add file extensions such that the shell scripts end in ".sh", and the configurations in ".config" and the other files in ".txt".

Regards

Nathan

**Comment by gilesheron** [comment]
yeah - was thinking about that last night (largely because if/when I write scripts to auto-generate stuff then it makes sense to have e.g. xrvr-a.sh to start xrvr-a and xrvr-a.config as xrvr-a's config).  will fix it today.
